---
abstract: 'Usable mock class'
author:
  - 'Viacheslav Tykhanovskyi, C<vti@cpan.org>.'
build_requires:
  Test::Fatal: 0
  Test::More: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.3, CPAN::Meta::Converter version 2.130880'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: test-monkeymock
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Test::MonkeyMock:
    file: lib/Test/MonkeyMock.pm
    version: 0.01
requires:
  Carp: 0
resources:
  bugtracker: https://github.com/vti/test-monkeymock/issues
  homepage: https://github.com/vti/test-monkeymock
  repository: git://github.com/vti/test-monkeymock.git
version: 0.01
x_contributors:
  - 'vti <viacheslav.t@gmail.com>'
