---
abstract: 'Usable mock class'
author:
  - 'Viacheslav Tykhanovskyi, C<viacheslav.t@gmail.com>'
build_requires:
  Test::Fatal: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v2.1.1, CPAN::Meta::Converter version 2.142690'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-MonkeyMock
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Test::MonkeyMock:
    file: lib/Test/MonkeyMock.pm
    version: '0.08'
requires:
  Carp: '0'
  Storable: '0'
resources:
  bugtracker: https://github.com/vti/test-monkeymock/issues
  homepage: https://github.com/vti/test-monkeymock
  repository: git://github.com/vti/test-monkeymock.git
version: '0.08'
